accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='home'),
    path('post/<int:pk>/', views.BlogDetailView.as_view(), name='detail'),
    path('post/new/', views.BlogCreateView.as_view(), name='new_post'),
    path('post/<int:pk>/edit/',
         views.BlogUpdateView.as_view(),name='edit'),
    path('post/<int:pk>/delete/',
         views.BlogDeleteView.as_view(), name='delete'),
]

newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from enum import unique
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):

    class Status(models.TextChoices):
        PUBLISHED = 'PB', 'Published'
        DRAFT = 'DF', 'Draft'

    title = models.CharField(max_length = 200,
                             unique_for_date='created')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=2,
                              default=Status.DRAFT,
                              choices=Status.choices)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:detail',
                       args=[str(self.id)])

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Post
from django.urls import reverse_lazy


class BlogListView(ListView):
    model = Post
    template_name = 'home.html'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'detail.html'
    context_object_name = 'post'


class BlogCreateView(CreateView):
    model = Post
    template_name = 'new_post.html'
    fields = ['title', 'author', 'body']


class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'edit.html'


class BlogDeleteView(DeleteView):
    model = Post
    template_name = "delete.html"
    success_url = reverse_lazy('blog:home')

templates/base.html
{% load static %}


<!DOCTYPE html>
<html>
  <head>
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css2?family=Encode+Sans:wdth,wght@75..125,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    <div class="header">
      <a class="link" href="{% url "blog:home" %}">My blog</a>
    </div> 
    <div id="nav-left">
      {% block content %}
      {% endblock %}
    </div>
    <div id="nav-right">
      {% if user.is_authenticated %}
        <p>Hello {{ user.username }}.</p>
        <p>
          <a class="link" href="{% url "blog:new_post" %}">+ Add New Post</a>
        </p>
        {% block right %}
        {% endblock %}
        <p>
          <a class="link" href="{% url "logout" %}">logout</a>
        </p>
      {% else %}
        <p>You are not logged in.</p>
        <p>
          <a class="link" href="{% url "login" %}">
            login
          </a>
        </p>
      {% endif %} 
    </div>
  </body>
</html>

templates/delete.html
{% extends "base.html" %}


{% block title %}
  Delete
{% endblock %}

{% block content %}
  <h1>Delete post</h1>
  <form action="" method="post">
    {% csrf_token %}
    <p>
      Are you sure you want to delete "{{ post.title }}"?
    </p>
    <input type="submit" value="Confirm" />
  </form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}


{% block title %}
  Blog detail
{% endblock %}
{% block content %}
  <div class="post-entry">
    <h2>Post "{{ post.title }}" by {{ post.author }}.</h2>
    <p class="text" >{{ post.body }}</p>
  </div>
{% endblock %}
{% block right %}
  <p>
    <a class="link" href="{% url "blog:edit" post.pk %}">
      Edit Blog Post
    </a>
  </p>
  <p>
    <a class="link" href="{% url "blog:delete" post.pk %}">
      Delete Blog Post
    </a>
  </p>
{% endblock %}

templates/edit.html
{% extends "base.html" %}


{% block title %}
  Edit
{% endblock %}
{% block content %}
  <h1>Edit post</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
  </form>
{% endblock %}

templates/home.html
{% extends "base.html" %}


{% block title %}
  blog home
{% endblock %}
{% block content %}
  {% for post in object_list %}
    <div class="post-entry">
      <h2><a class="link" href="{% url "blog:detail" post.pk %}">{{ post.title }}</a></h2>
      <p class="text" >{{ post.body|truncatewords_html:10 }}</p>
    </div>
  {% endfor %}
{% endblock %}

templates/new_post.html
{% extends 'base.html' %}


{% block title %}
  add post
{% endblock %}
{% block content %}
  <h1>New post</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
{% endblock %}

templates/signup.html
{% extends "base.html" %}


{% block title %}
  sign up
{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}